# General information
site_name: Wakweli - Whitepaper
site_url: https://whitepaper.wakweli.com
site_description: Wakweli is a decentralized protocol designed to restore trust in the digital ecosystem by verifying and certifying the authenticity of digital information.
site_author: Wakweli Foundation
copyright: (c) Wakweli Foundation 2025

# Theme
theme:
  name: material
  logo: assets/favicon.svg
  favicon: assets/favicon.svg
  features:
    - navigation.instant
    - navigation.footer
  font:
    text: Montserrat Light
  palette: 
    - scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

# Extensions
markdown_extensions:
  - attr_list

# Page tree
nav:
  - Project Overview: index.md
  - Introduction: introduction.md
  - Technology: technology.md
  - $WAKU Tokenomics: waku.md
  - Alpha: alpha.md
  - Our Story & Core Values: about.md
  - Wakweli Foundation: foundation.md
  - Roadmap: roadmap.md
  - Conclusion: conclusion.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/wakwelichain
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/wakweli
    - icon: fontawesome/brands/discord
      link: https://discord.wakweli.com
    - icon: fontawesome/brands/telegram
      link: https://t.me/+J7yjH5SE8E42ZWM8
